
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\trax

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# environment variables
environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 2013 Win64"
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release

# scripts that run after cloning repository
install:

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
   - x86
   - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
    - ReleaseVS13
    - ReleaseVS15

build:
  project: PACKAGE.vcxproj
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  verbosity: quiet|minimal|normal|detailed

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\trax
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%P% -DBUILD_CLIENT=ON -DBUILD_VERSION=%APPVEYOR_BUILD_VERSION% -DCMAKE_BUILD_TYPE=Release

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: TraX-*.zip

  # pushing all *.nupkg files in build directory recursively
#  - path: '**\*.nupkg'


#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:

    # FTP deployment provider settings
  - provider: FTP
    protocol: ftp|ftps|sftp
    host: box.vicos.si
    username: appveyor
    password:
      secure: wjVh1vJoXkFXCoFm/KgsAg==
    folder: /vot/trax/
    application:
    active_mode: false
    beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
    debug: true     # show complete FTP log

    # Deploying to NuGet feed
#  - provider: NuGet
#    server: https://my.nuget.server/feed
#    api_key:
#      secure: FYWX6NfjZIVw==
#    skip_symbols: false
#    symbol_server: https://your.symbol.server/feed
#    artifact: MyPackage.nupkg

    # Deploy to GitHub Releases
#  - provider: GitHub
#    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#    draft: false
#    prerelease: false
#    on:
#      branch: master                # release from master branch only
#      appveyor_repo_tag: true       # deploy on tag push only

# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
#  - do something

# on build failure
#on_failure:
#  - do something

# after build failure or success
#on_finish:
#  - do something

notifications:

  # Email
  - provider: Email
    to:
      - luka.cehovin@gmail.com
    subject: 'TraX Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

